gpt-5:
    model: gpt-5
    endpoints: null
    api_type: gpt5
    parallel: 32
    temperature: 1

gpt-5-non-reasoning:
    model: gpt-5
    endpoints: null
    api_type: gpt5
    parallel: 32
    temperature: 1
    reasoning:
        effort: low
    text:
        verbosity: low

gpt-4.1-2025-04-14:
    model: gpt-4.1-2025-04-14
    endpoints: null
    api_type: openai
    parallel: 64
    max_tokens: 32000
    temperature: 0.0

# JUDGE MODEL USING RECOMMENDED SETTINGS FROM README
gpt-4.1:
    model: gpt-4.1
    endpoints: null
    api_type: openai
    parallel: 64
    max_tokens: 32000
    temperature: 0.0

gemini-2.5-flash:
    model: gemini-2.5-flash
    endpoints: null
    api_type: gemini
    parallel: 50
    thinking_budget: 0

deepseek-v3.2-exp:
    model: deepseek-chat
    endpoints:
        - api_key: "API_KEY"
    api_type: deepseek
    parallel: 32
    max_tokens: 8192

claude-sonnet-4-5-20250929:
    model: claude-sonnet-4-5-20250929
    endpoints: null
    max_tokens: 20000
    api_type: anthropic
    parallel: 2
    temperature: 1.0
    thinking: false

grok-4-fast-non-reasoning:
    model: grok-4-fast-non-reasoning
    endpoints:
        - api_base: https://api.x.ai/v1
          api_key: "API_KEY"
    api_type: openai
    parallel: 32
    max_tokens: 8192
    temperature: 0.0

mistral-medium-2508:
    model: mistral-medium-2508
    endpoints: null
    api_type: mistral
    parallel: 32
    max_tokens: 8192
    temperature: 0.0


qwen3-30b-a3b:
    model: Qwen/Qwen3-30B-A3B-Instruct-2507
    endpoints:
        - api_base: http://0.0.0.0:8000/v1
          api_key: '-'
    api_type: openai
    parallel: 32
    max_tokens: 8196
    temperature: 0.7
    top_p: 0.8
    top_k: 20
    min_p: 0.0

qwen3-235b:
    model: Qwen/Qwen3-235B-A22B-Instruct-2507
    endpoints:
        - api_base: http://0.0.0.0:8000/v1
          api_key: '-'
    api_type: openai
    parallel: 16
    max_tokens: 8196
    temperature: 0.7
    top_p: 0.8
    top_k: 20
    min_p: 0.0

l1-235b:
    model: locailabs/L1-235B
    endpoints:
        - api_base: http://0.0.0.0:8000/v1
          api_key: '-'
    api_type: openai
    parallel: 16
    max_tokens: 8196
    temperature: 0.7
    top_p: 0.8
    top_k: 20
    min_p: 0.0